export type AbilityTier = 0 | 1 | 2 | 3;
export type AbilityType = 'passive' | 'active' | 'reaction';

export interface Ability {
	id: string;
	name: string;
	skillId: string;
	tier: AbilityTier;
	type: AbilityType;
	description: string;
	/** Бонус к значению навыка (по умолчанию — к skillId) */
	skillBonus?: number;
	/** Если бонус идёт к другому навыку, а не к skillId */
	bonusTo?: string;
	/** Для прогрессирующих умений (например, «Острый глаз I/II/III»).
	 *  Работает только максимальный бонус в группе, не суммируется. */
	progressiveGroup?: string;
	/** Context-only bonus: it applies only to that kind of check, not every check for the skill. */
	bonusContext?: string;
}

export const ABILITY_THRESHOLDS: Record<AbilityTier, number> = {
	0: 0,
	1: 42,
	2: 54,
	3: 72
};

export const ABILITIES: Ability[] = [
	// ═══════════════ ИНТЕЛЛЕКТ ═══════════════

	// ─── Разрушение ───
	{ id: 'destruction_base', name: 'Базовый эффект', skillId: 'destruction', tier: 0, type: 'passive',
		description: 'Каждое вложенное очко навыка увеличивает урон заклинаний Разрушения на +1 и даёт +1 к проверкам попадания.' },
	{ id: 'destruction_double', name: 'Двойное разрушение', skillId: 'destruction', tier: 1, type: 'passive',
		description: 'При сотворении заклинания с двух рук урон увеличивается на 1 кость.' },
	{ id: 'destruction_apprentice', name: 'Ученик школы разрушения', skillId: 'destruction', tier: 1, type: 'passive',
		description: 'Заклинания школы разрушения тратят на 1 живу меньше (не менее 1).' },
	{ id: 'destruction_flame', name: 'Усиленное пламя', skillId: 'destruction', tier: 2, type: 'passive',
		description: 'Огненные заклинания наносят дополнительную кость урона.' },
	{ id: 'destruction_frost', name: 'Усиленный мороз', skillId: 'destruction', tier: 2, type: 'passive',
		description: 'Заклинания холода наносят дополнительную кость урона.' },
	{ id: 'destruction_lightning', name: 'Усиленные молнии', skillId: 'destruction', tier: 2, type: 'passive',
		description: 'Заклинания электричества наносят дополнительную кость урона.' },
	{ id: 'destruction_runemaster', name: 'Мастер рун', skillId: 'destruction', tier: 2, type: 'passive',
		description: 'Руны можно наносить на 4 сажени дальше.' },
	{ id: 'destruction_adept', name: 'Адепт школы разрушения', skillId: 'destruction', tier: 2, type: 'passive',
		description: 'Заклинания школы разрушения тратят на 2 живы меньше (не менее 1).' },
	{ id: 'destruction_shockwave', name: 'Ударная волна', skillId: 'destruction', tier: 2, type: 'passive',
		description: 'Заклинания с двух рук заставляют противника потерять равновесие.' },
	{ id: 'destruction_burning', name: 'Жаркое пламя', skillId: 'destruction', tier: 3, type: 'passive',
		description: 'Урон от огня обращает противника в бегство, если у него мало здоровья.' },
	{ id: 'destruction_deepfreeze', name: 'Глубокая заморозка', skillId: 'destruction', tier: 3, type: 'passive',
		description: 'Урон от холода парализует противника при низком здоровье.' },
	{ id: 'destruction_disintegrate', name: 'Дезинтеграция', skillId: 'destruction', tier: 3, type: 'passive',
		description: 'Урон от электричества дезинтегрирует противника при низком здоровье.' },
	{ id: 'destruction_master', name: 'Мастер школы разрушения', skillId: 'destruction', tier: 3, type: 'passive',
		description: 'Заклинания школы разрушения тратят на 4 живы меньше (не менее 1).' },

	// ─── Изменение ───
	{ id: 'transmutation_base', name: 'Базовый эффект', skillId: 'transmutation', tier: 0, type: 'passive',
		description: 'Каждые 5 очков навыка: +1 раунд к длительности заклинаний Изменения и +1 к проверкам преодоления магического сопротивления.' },
	{ id: 'transmutation_double', name: 'Двойное изменение', skillId: 'transmutation', tier: 1, type: 'passive',
		description: 'При сотворении с двух рук удваивается длительность большинства заклинаний Изменения.' },
	{ id: 'transmutation_apprentice', name: 'Ученик школы изменения', skillId: 'transmutation', tier: 1, type: 'passive',
		description: 'Заклинания школы изменения тратят на 1 живу меньше (не менее 1).' },
	{ id: 'transmutation_mage_armor', name: 'Магическая броня', skillId: 'transmutation', tier: 1, type: 'passive',
		description: 'Защитные заклинания действуют на +2, если заклинатель не носит доспехов.' },
	{ id: 'transmutation_resist', name: 'Сопротивление магии', skillId: 'transmutation', tier: 1, type: 'passive',
		description: 'Урон от заклинаний уменьшается на 1к6.' },
	{ id: 'transmutation_adept', name: 'Адепт школы изменения', skillId: 'transmutation', tier: 2, type: 'passive',
		description: 'Заклинания школы изменения тратят на 2 живы меньше (не менее 1).' },
	{ id: 'transmutation_mage_armor2', name: 'Магическая броня II', skillId: 'transmutation', tier: 2, type: 'passive',
		description: 'Защитные заклинания действуют на +4, если нет доспехов.' },
	{ id: 'transmutation_resist2', name: 'Сопротивление магии II', skillId: 'transmutation', tier: 2, type: 'passive',
		description: 'Урон от заклинаний уменьшается на 2к6.' },
	{ id: 'transmutation_master', name: 'Мастер школы изменения', skillId: 'transmutation', tier: 3, type: 'passive',
		description: 'Заклинания школы изменения тратят на 4 живы меньше (не менее 1).' },
	{ id: 'transmutation_mage_armor3', name: 'Магическая броня III', skillId: 'transmutation', tier: 3, type: 'passive',
		description: 'Защитные заклинания действуют на +6, если нет доспехов.' },
	{ id: 'transmutation_resist3', name: 'Сопротивление магии III', skillId: 'transmutation', tier: 3, type: 'passive',
		description: 'Урон от заклинаний уменьшается на 3к6.' },
	{ id: 'transmutation_atronach', name: 'Атронах', skillId: 'transmutation', tier: 3, type: 'active',
		description: '1/продолжительный отдых. При успешной проверке заклинатель поглощает урон от заклинаний полностью и восстанавливает себе живу на величину урона.' },

	// ─── Колдовство ───
	{ id: 'witchcraft_base', name: 'Базовый эффект', skillId: 'witchcraft', tier: 0, type: 'passive',
		description: 'Каждое очко навыка: +2 живучести призванным существам и +1 к проверкам преодоления сопротивления проклятиям.' },
	{ id: 'witchcraft_double', name: 'Двойное колдовство', skillId: 'witchcraft', tier: 1, type: 'passive',
		description: 'При сотворении с двух рук заклинания действуют вдвое дольше.' },
	{ id: 'witchcraft_apprentice', name: 'Ученик школы колдовства', skillId: 'witchcraft', tier: 1, type: 'passive',
		description: 'Заклинания школы колдовства тратят на 1 живу меньше (не менее 1).' },
	{ id: 'witchcraft_mystic_summon', name: 'Мистический призыв', skillId: 'witchcraft', tier: 1, type: 'passive',
		description: 'Урон призванного оружия повышается на 1к6.' },
	{ id: 'witchcraft_adept', name: 'Адепт школы колдовства', skillId: 'witchcraft', tier: 2, type: 'passive',
		description: 'Заклинания школы колдовства тратят на 2 живы меньше (не менее 1).' },
	{ id: 'witchcraft_necromancy', name: 'Некромантия', skillId: 'witchcraft', tier: 2, type: 'active',
		description: 'Вы можете поднимать нежить на дистанции 4 сажени, на 1 минуту.' },
	{ id: 'witchcraft_summoner', name: 'Призыватель', skillId: 'witchcraft', tier: 2, type: 'passive',
		description: 'Позволяет поднимать нежить дальше на 4 сажени.' },
	{ id: 'witchcraft_elemental', name: 'Элементалия', skillId: 'witchcraft', tier: 2, type: 'passive',
		description: 'Призванные элементали живут вдвое дольше, урон +2к6.' },
	{ id: 'witchcraft_banish', name: 'Изгнание в Навь', skillId: 'witchcraft', tier: 2, type: 'passive',
		description: 'Призванное оружие изгоняет призванных существ и обращает поднятую нежить в бегство.' },
	{ id: 'witchcraft_master', name: 'Мастер школы колдовства', skillId: 'witchcraft', tier: 3, type: 'passive',
		description: 'Заклинания школы колдовства тратят на 4 живы меньше (не менее 1).' },
	{ id: 'witchcraft_dark_souls', name: 'Тёмные души', skillId: 'witchcraft', tier: 3, type: 'passive',
		description: 'Поднятая нежить получает вдвое больше живучести.' },
	{ id: 'witchcraft_elemental_power', name: 'Сила стихий', skillId: 'witchcraft', tier: 3, type: 'passive',
		description: 'Призванные элементали получают вдвое больше живучести и костей урона.' },
	{ id: 'witchcraft_paired', name: 'Парные души', skillId: 'witchcraft', tier: 3, type: 'passive',
		description: 'Можно поднять двух элементалей или две нежити.' },

	// ─── Иллюзия ───
	{ id: 'illusion_base', name: 'Базовый эффект', skillId: 'illusion', tier: 0, type: 'passive',
		description: 'Каждое очко: +1 к сложности избавления от иллюзий и +1 раунд длительности.' },
	{ id: 'illusion_apprentice', name: 'Ученик школы иллюзий', skillId: 'illusion', tier: 1, type: 'passive',
		description: 'Заклинания школы иллюзий тратят на 1 живу меньше (не менее 1).' },
	{ id: 'illusion_double', name: 'Двойная иллюзия', skillId: 'illusion', tier: 1, type: 'passive',
		description: 'При сотворении с двух рук удваивается длительность.' },
	{ id: 'illusion_animals', name: 'Обман животных', skillId: 'illusion', tier: 1, type: 'passive',
		description: 'Заклинатель может применять заклинания на животных.' },
	{ id: 'illusion_eyes', name: 'Обман людских глаз', skillId: 'illusion', tier: 1, type: 'passive',
		description: '+5 к проверкам заклинаний с визуальным эффектом.' },
	{ id: 'illusion_hypnosis', name: 'Гипнотический взгляд', skillId: 'illusion', tier: 1, type: 'passive',
		description: 'Заклинания успокоения действуют с +5.' },
	{ id: 'illusion_adept', name: 'Адепт школы иллюзий', skillId: 'illusion', tier: 2, type: 'passive',
		description: 'Заклинания школы иллюзий тратят на 2 живы меньше (не менее 1).' },
	{ id: 'illusion_zhut_science', name: 'Наука Жути', skillId: 'illusion', tier: 2, type: 'passive',
		description: 'Заклинания Жути действуют вдвое дольше, +5 к модификатору.' },
	{ id: 'illusion_silent', name: 'Бесшумные заклинания', skillId: 'illusion', tier: 2, type: 'passive',
		description: 'Заклинания любой школы теперь произносятся бесшумно.' },
	{ id: 'illusion_master', name: 'Мастер школы иллюзий', skillId: 'illusion', tier: 3, type: 'passive',
		description: 'Заклинания школы иллюзий тратят на 4 живы меньше (не менее 1).' },
	{ id: 'illusion_frenzy', name: 'Неистовство', skillId: 'illusion', tier: 3, type: 'passive',
		description: 'Заклинания бешенства действуют с +5.' },
	{ id: 'illusion_mind_master', name: 'Мастер разума', skillId: 'illusion', tier: 3, type: 'passive',
		description: 'Заклинания иллюзий действуют на нежить, разумные механизмы и драконов.' },

	// ─── Восстановление ───
	{ id: 'restoration_base', name: 'Базовый эффект', skillId: 'restoration', tier: 0, type: 'passive',
		description: 'Каждое очко: +1 к объёму лечения и +1 к проверкам против нежити.' },
	{ id: 'restoration_double', name: 'Двойное восстановление', skillId: 'restoration', tier: 1, type: 'passive',
		description: 'При сотворении с двух рук урон (лечение) увеличивается на 1 кость.' },
	{ id: 'restoration_apprentice', name: 'Ученик школы восстановления', skillId: 'restoration', tier: 1, type: 'passive',
		description: 'Заклинания школы восстановления тратят на 1 живу меньше (не менее 1).' },
	{ id: 'restoration_replenish', name: 'Восполнение', skillId: 'restoration', tier: 1, type: 'passive',
		description: 'Очки живы восстанавливаются быстрее на 1к6.' },
	{ id: 'restoration_adept', name: 'Адепт школы восстановления', skillId: 'restoration', tier: 2, type: 'passive',
		description: 'Заклинания школы восстановления тратят на 2 живы меньше (не менее 1).' },
	{ id: 'restoration_replenish2', name: 'Восполнение II', skillId: 'restoration', tier: 2, type: 'passive',
		description: 'Очки живы восстанавливаются быстрее на 2к6.' },
	{ id: 'restoration_respite', name: 'Передышка', skillId: 'restoration', tier: 2, type: 'passive',
		description: 'Заклинания восстановления также восстанавливают бодрость на 2к6.' },
	{ id: 'restoration_absorb', name: 'Оберег-поглотитель', skillId: 'restoration', tier: 2, type: 'passive',
		description: 'Обереги при ударе восполняют живу в размере половины урона.' },
	{ id: 'restoration_necromage', name: 'Некромаг', skillId: 'restoration', tier: 2, type: 'passive',
		description: 'Заклинания школы восстановления эффективнее против нежити.' },
	{ id: 'restoration_master', name: 'Мастер школы восстановления', skillId: 'restoration', tier: 3, type: 'passive',
		description: 'Заклинания школы восстановления тратят на 4 живы меньше (не менее 1).' },
	{ id: 'restoration_naviescape', name: 'Бегство от Нави', skillId: 'restoration', tier: 3, type: 'active',
		description: 'Когда живучесть ≤ 10, автоматически восстанавливаете 2/3 живучести. 1 раз до продолжительного отдыха.' },

	// ─── Зачарование ───
	{ id: 'enchantment_base', name: 'Базовый эффект', skillId: 'enchantment', tier: 0, type: 'passive',
		description: 'Каждое очко: +1 к шансу успеха при зачаровании.' },
	{ id: 'enchantment_enchanter', name: 'Зачарователь', skillId: 'enchantment', tier: 1, type: 'passive',
		description: 'Сила наложенных чар увеличивается на 5.' },
	{ id: 'enchantment_saving', name: 'Экономия кристаллов живы', skillId: 'enchantment', tier: 1, type: 'active',
		description: 'Проведя ритуал (30 минут), вы можете зарядить магический предмет.' },
	{ id: 'enchantment_fire', name: 'Огненные чары', skillId: 'enchantment', tier: 1, type: 'passive',
		description: 'Огненные чары на оружии и доспехах сильнее на 1к6.' },
	{ id: 'enchantment_enchanter2', name: 'Зачарователь II', skillId: 'enchantment', tier: 2, type: 'passive',
		description: 'Сила наложенных чар увеличивается на 10.' },
	{ id: 'enchantment_frost', name: 'Морозные чары', skillId: 'enchantment', tier: 2, type: 'passive',
		description: 'Морозные чары сильнее на 1к6.' },
	{ id: 'enchantment_storm', name: 'Грозовые чары', skillId: 'enchantment', tier: 2, type: 'passive',
		description: 'Грозовые чары сильнее на 1к6.' },
	{ id: 'enchantment_enchanter3', name: 'Зачарователь III', skillId: 'enchantment', tier: 3, type: 'passive',
		description: 'Сила наложенных чар увеличивается на 15.' },
	{ id: 'enchantment_life', name: 'Чары живы', skillId: 'enchantment', tier: 3, type: 'passive',
		description: 'Чары здоровья, магии и выносливости сильнее на 1к8.' },
	{ id: 'enchantment_double_effect', name: 'Дополнительный эффект', skillId: 'enchantment', tier: 3, type: 'passive',
		description: 'На один предмет можно наложить два вида чар.' },

	// ─── Наблюдательность ───
	{ id: 'perception_base', name: 'Базовый эффект', skillId: 'perception', tier: 0, type: 'passive',
		description: 'Каждое очко навыка даёт +1 к проверкам Наблюдательности.' },
	{ id: 'perception_sharp_eye', name: 'Острый глаз', skillId: 'perception', tier: 1, type: 'passive',
		description: '+5 к проверкам Наблюдательности.', skillBonus: 5, progressiveGroup: 'perception_eye' },
	{ id: 'perception_magic_sense', name: 'Магическое чутьё', skillId: 'perception', tier: 1, type: 'passive',
		description: 'Вы чувствуете магию в радиусе 5 саженей; определяете школу активного заклинания.' },
	{ id: 'perception_sharp_eye2', name: 'Острый глаз II', skillId: 'perception', tier: 2, type: 'passive',
		description: '+10 к проверкам Наблюдательности.', skillBonus: 10, progressiveGroup: 'perception_eye' },
	{ id: 'perception_magic_sense2', name: 'Магическое чутьё II', skillId: 'perception', tier: 2, type: 'passive',
		description: 'Радиус 10 саженей; определяете примерную силу магического следа.' },
	{ id: 'perception_tracker', name: 'Следопыт', skillId: 'perception', tier: 2, type: 'active',
		description: 'За 1 минуту находите следы существа или магии в радиусе 30 м. Проверка Наблюдательности.' },
	{ id: 'perception_sharp_eye3', name: 'Острый глаз III', skillId: 'perception', tier: 3, type: 'passive',
		description: '+15 к проверкам Наблюдательности.', skillBonus: 15, progressiveGroup: 'perception_eye' },
	{ id: 'perception_allseeing', name: 'Всевидящий взор', skillId: 'perception', tier: 3, type: 'active',
		description: '1/день. На 1 минуту видите всё в радиусе 20 саженей: сквозь стены, иллюзии, тьму. Стоит 2 живы.' },

	// ─── Выживание ───
	{ id: 'survival_base', name: 'Базовый эффект', skillId: 'survival', tier: 0, type: 'passive',
		description: 'Каждое очко: +1 к проверкам поиска пищи, воды, укрытий, ориентирования и следопытства.' },
	{ id: 'survival_hunter', name: 'Охотник-собиратель', skillId: 'survival', tier: 1, type: 'passive',
		description: 'Находите пропитание для группы из 4 человек за 1 час без проверки в обычной местности.' },
	{ id: 'survival_tracker', name: 'Умелый следопыт', skillId: 'survival', tier: 1, type: 'passive',
		description: '+5 к проверкам Наблюдательности при поиске следов людей или животных.',
		skillBonus: 5, bonusTo: 'perception', progressiveGroup: 'survival_tracker', bonusContext: 'tracking' },
	{ id: 'survival_camp', name: 'Привал', skillId: 'survival', tier: 1, type: 'active',
		description: 'За 1 час и 2 бодрости организуете лагерь: +5 к Скрытности для всех в нём до утра.' },
	{ id: 'survival_master_tracker', name: 'Мастер следопыт', skillId: 'survival', tier: 2, type: 'passive',
		description: '+10 к поиску следов; определяете состояние существа (ранено, несёт груз, бежит).',
		skillBonus: 10, bonusTo: 'perception', progressiveGroup: 'survival_tracker', bonusContext: 'tracking' },
	{ id: 'survival_shelter', name: 'Надёжное убежище', skillId: 'survival', tier: 2, type: 'active',
		description: 'За 2 часа и 3 бодрости укрытие: короткий отдых даёт +1к4 живучести, длительный снимает +1 Истощение.' },
	{ id: 'survival_terrain', name: 'Чтение местности', skillId: 'survival', tier: 2, type: 'passive',
		description: 'Определяете воду, опасных зверей и людей в радиусе 2 км по поведению птиц и растений.' },
	{ id: 'survival_instinct', name: 'Инстинкт выжившего', skillId: 'survival', tier: 3, type: 'passive',
		description: 'Игнорируете штрафы Изнеможения от голода, жажды и холода. +10 к избавлению от природных ядов и болезней.' },
	{ id: 'survival_land_call', name: 'Зов земли', skillId: 'survival', tier: 3, type: 'active',
		description: '1/день. Ритуал (1 час, 4 бодрости) — находите редкий ресурс в радиусе 5 км.' },
	{ id: 'survival_merge', name: 'Слияние с природой', skillId: 'survival', tier: 3, type: 'active',
		description: '1/день. На 10 минут: +20 к Скрытности в лесу, звери вас не замечают. Стоит 2 бодрости.' },

	// ─── Обращение с животными ───
	{ id: 'animal_base', name: 'Базовый эффект', skillId: 'animal_handling', tier: 0, type: 'passive',
		description: 'Каждое очко: +1 к проверкам общения, дрессировки, верховой езды и понимания животных.' },
	{ id: 'animal_body_lang', name: 'Язык тела', skillId: 'animal_handling', tier: 1, type: 'passive',
		description: 'Без проверки понимаете базовые эмоции животного (страх, агрессию, голод, любопытство).' },
	{ id: 'animal_calm', name: 'Успокоить зверя', skillId: 'animal_handling', tier: 1, type: 'active',
		description: 'Действие + проверка. Успокаиваете одно дикое животное (не больше волка) на 1 минуту. Стоит 2 бодрости.' },
	{ id: 'animal_tame', name: 'Приручение (малое)', skillId: 'animal_handling', tier: 1, type: 'active',
		description: 'Ритуал (1 час, 4 бодрости). Приручаете дикое животное на постоянную основу.' },
	{ id: 'animal_rider', name: 'Наездник', skillId: 'animal_handling', tier: 2, type: 'passive',
		description: 'Управляете верховым животным без проверки в спокойных условиях. Нет штрафов за стрельбу верхом.' },
	{ id: 'animal_trainer', name: 'Дрессировщик', skillId: 'animal_handling', tier: 2, type: 'passive',
		description: 'Обучаете прирученное животное до 3 сложных команд за неделю тренировок.' },
	{ id: 'animal_messenger', name: 'Звериный посланник', skillId: 'animal_handling', tier: 2, type: 'active',
		description: 'Ритуал (10 минут, 2 бодрости). Отправляете небольшое животное с письмом на 30 км за 1 день.' },
	{ id: 'animal_lord', name: 'Властелин зверей', skillId: 'animal_handling', tier: 3, type: 'passive',
		description: '+10 к Обращению с животными, сложность приручения −10. Можно временно подчинить стаю волков или медведя.' },
	{ id: 'animal_warbeast', name: 'Боевой зверь', skillId: 'animal_handling', tier: 3, type: 'active',
		description: 'Ритуал (1 день). Обучаете животное боевым командам — оно сражается как полноценный союзник.' },
	{ id: 'animal_pack', name: 'Призыв стаи', skillId: 'animal_handling', tier: 3, type: 'active',
		description: '1/день. В лесу или степи: 1к4+2 волков или 1 медведь приходят через 1к4 раунда. Стоит 4 бодрости.' },

	// ═══════════════ СИЛА ═══════════════

	// ─── Кузнечное дело ───
	{ id: 'smithing_base', name: 'Базовый эффект', skillId: 'smithing', tier: 0, type: 'passive',
		description: 'Каждое очко: +1 к восстанавливаемой прочности и +1 к проверкам создания предметов.' },
	{ id: 'smithing_quality_repair', name: 'Качественный ремонт', skillId: 'smithing', tier: 1, type: 'passive',
		description: 'При ремонте доспехов или оружия восстанавливаете на 1к4 прочности больше.' },
	{ id: 'smithing_simple', name: 'Простое оружие и доспехи', skillId: 'smithing', tier: 1, type: 'passive',
		description: 'Умеете изготавливать простое оружие, железные и кожаные доспехи, деревянные щиты.' },
	{ id: 'smithing_improved_weapon', name: 'Улучшенное оружие', skillId: 'smithing', tier: 2, type: 'passive',
		description: 'Созданное вами оружие даёт +1 к атаке и урону.' },
	{ id: 'smithing_improved_armor', name: 'Улучшенная броня', skillId: 'smithing', tier: 2, type: 'passive',
		description: 'Созданные вами доспехи дают +2 к Броне.' },
	{ id: 'smithing_jewelry', name: 'Ювелирные украшения', skillId: 'smithing', tier: 2, type: 'passive',
		description: 'Умеете создавать кулоны, кольца, серьги, подвески.' },
	{ id: 'smithing_temp_improve', name: 'Временное улучшение', skillId: 'smithing', tier: 2, type: 'active',
		description: 'За 10 минут и 3 бодрости: +1 к урону оружия или +1 к Броне доспеха до конца следующего боя.' },
	{ id: 'smithing_magic_weapon', name: 'Магическое оружие', skillId: 'smithing', tier: 3, type: 'passive',
		description: 'Умеете создавать оружие со стихийным уроном и бонусом +2 к атаке и урону.' },
	{ id: 'smithing_magic_armor', name: 'Магические доспехи', skillId: 'smithing', tier: 3, type: 'passive',
		description: 'Умеете создавать доспехи с защитой от стихий и +4 к Броне.' },
	{ id: 'smithing_magic_jewelry', name: 'Магические украшения', skillId: 'smithing', tier: 3, type: 'passive',
		description: 'Умеете создавать украшения с защитными или атакующими свойствами.' },
	{ id: 'smithing_legendary', name: 'Легендарная ковка', skillId: 'smithing', tier: 3, type: 'active',
		description: 'Ритуал. Создаёте предметы с уникальными свойствами. Требует редких ингредиентов.' },

	// ─── Тяжёлая броня ───
	{ id: 'heavy_armor_base', name: 'Базовый эффект', skillId: 'heavy_armor', tier: 0, type: 'passive',
		description: 'Каждое очко: +1 к Броне от тяжёлой брони (не более +6 суммарно).' },
	{ id: 'heavy_armor_prof', name: 'Владение тяжёлой бронёй', skillId: 'heavy_armor', tier: 1, type: 'passive',
		description: 'Броня от тяжёлой брони увеличивается на +2.' },
	{ id: 'heavy_armor_prof2', name: 'Владение тяжёлой бронёй II', skillId: 'heavy_armor', tier: 2, type: 'passive',
		description: 'Бонус увеличивается до +4.' },
	{ id: 'heavy_armor_iron_fists', name: 'Железные кулаки', skillId: 'heavy_armor', tier: 2, type: 'passive',
		description: 'В полном тяжёлом доспехе рукопашные атаки наносят 1к6 + мод. тяжёлой брони.' },
	{ id: 'heavy_armor_padding', name: 'Мягкая подкладка', skillId: 'heavy_armor', tier: 2, type: 'passive',
		description: 'Снижаете получаемый физический урон на 1к8 + половина модификатора тяжёлой брони.' },
	{ id: 'heavy_armor_prof3', name: 'Владение тяжёлой бронёй III', skillId: 'heavy_armor', tier: 3, type: 'passive',
		description: 'Бонус увеличивается до +6.' },
	{ id: 'heavy_armor_center', name: 'Центр тяжести', skillId: 'heavy_armor', tier: 3, type: 'passive',
		description: 'Вас нельзя сдвинуть с места или сбить с ног против вашей воли.' },
	{ id: 'heavy_armor_reflect', name: 'Отражение урона', skillId: 'heavy_armor', tier: 3, type: 'reaction',
		description: '1/раунд. Проверка Стойкости: при успехе атакующий получает половину урона.' },

	// ─── Блокирование ───
	{ id: 'blocking_base', name: 'Базовый эффект', skillId: 'blocking', tier: 0, type: 'passive',
		description: 'Каждое очко: +1 к Броне от щита (не более +6) и +1 к проверкам блокирования.' },
	{ id: 'blocking_shield_bearer', name: 'Щитоносец', skillId: 'blocking', tier: 1, type: 'passive',
		description: '+2 к Броне сверх обычного бонуса щита.' },
	{ id: 'blocking_shield_bearer2', name: 'Щитоносец II', skillId: 'blocking', tier: 2, type: 'passive',
		description: 'Бонус увеличивается до +4.' },
	{ id: 'blocking_arrow_deflect', name: 'Отбивание стрел', skillId: 'blocking', tier: 2, type: 'reaction',
		description: 'Тратите 2 бодрости, чтобы отбить летящую стрелу (БД). Успех автоматический.' },
	{ id: 'blocking_bash', name: 'Силовой удар плашмя', skillId: 'blocking', tier: 2, type: 'active',
		description: 'Атака щитом 1к6 + мод. блокирования дробящего урона; цель может оглохнуть (Избавление Силы).' },
	{ id: 'blocking_shield_bearer3', name: 'Щитоносец III', skillId: 'blocking', tier: 3, type: 'passive',
		description: 'Бонус увеличивается до +6.' },
	{ id: 'blocking_elem_defense', name: 'Защита от стихий', skillId: 'blocking', tier: 3, type: 'passive',
		description: 'Щит блокирует стихийный урон: снижение на 1к6 + мод. блокирования.' },
	{ id: 'blocking_death_bash', name: 'Смертельный удар плашмя', skillId: 'blocking', tier: 3, type: 'active',
		description: 'Полный ход. Атака щитом наносит тройной урон (3к6 + мод. блокирования ×3). 1/бой.' },
	{ id: 'blocking_disarm', name: 'Обезоруживание', skillId: 'blocking', tier: 3, type: 'active',
		description: 'Противник должен пройти Избавление Силы или выбить оружие.' },
	{ id: 'blocking_living_hammer', name: 'Живой молот', skillId: 'blocking', tier: 3, type: 'active',
		description: 'В беге с щитом сбиваете противников с ног. Избавление Силы или цель падает.' },

	// ─── Двуручное оружие ───
	{ id: 'two_handed_base', name: 'Базовый эффект', skillId: 'two_handed', tier: 0, type: 'passive',
		description: 'Каждое очко: +1 к урону и +1 к атаке двуручным оружием.' },
	{ id: 'two_handed_barbarian', name: 'Варвар', skillId: 'two_handed', tier: 1, type: 'passive',
		description: 'Атака и урон увеличиваются на +2.' },
	{ id: 'two_handed_crusher', name: 'Крушитель', skillId: 'two_handed', tier: 1, type: 'passive',
		description: 'Атаки молотом или алебардой игнорируют 2 Броня.' },
	{ id: 'two_handed_barbarian2', name: 'Варвар II', skillId: 'two_handed', tier: 2, type: 'passive',
		description: 'Бонус увеличивается до +4.' },
	{ id: 'two_handed_crusher2', name: 'Крушитель II', skillId: 'two_handed', tier: 2, type: 'passive',
		description: 'Игнорируют 4 Броня.' },
	{ id: 'two_handed_champion', name: 'Стойка чемпиона', skillId: 'two_handed', tier: 2, type: 'passive',
		description: 'Силовые атаки тратят на 1 бодрость меньше.' },
	{ id: 'two_handed_deep_wounds', name: 'Глубокие раны', skillId: 'two_handed', tier: 2, type: 'passive',
		description: 'При критическом попадании накладываете состояние Руда (1к4 живучести/раунд).' },
	{ id: 'two_handed_barbarian3', name: 'Варвар III', skillId: 'two_handed', tier: 3, type: 'passive',
		description: 'Бонус увеличивается до +6.' },
	{ id: 'two_handed_crusher3', name: 'Крушитель III', skillId: 'two_handed', tier: 3, type: 'passive',
		description: 'Игнорируют 6 Броня.' },
	{ id: 'two_handed_champion2', name: 'Стойка чемпиона II', skillId: 'two_handed', tier: 3, type: 'passive',
		description: 'Силовые атаки тратят на 2 бодрости меньше (суммарно).' },
	{ id: 'two_handed_crushing', name: 'Сокрушительный удар', skillId: 'two_handed', tier: 3, type: 'passive',
		description: 'Силовые атаки наносят удвоенный модификатор двуручного оружия.' },

	// ─── Одноручное оружие ───
	{ id: 'one_handed_base', name: 'Базовый эффект', skillId: 'one_handed', tier: 0, type: 'passive',
		description: 'Каждое очко: +1 к урону и +1 к атаке одноручным оружием.' },
	{ id: 'one_handed_strong', name: 'Сильная рука', skillId: 'one_handed', tier: 1, type: 'passive',
		description: 'Атака и урон увеличиваются на +2.' },
	{ id: 'one_handed_strong2', name: 'Сильная рука II', skillId: 'one_handed', tier: 2, type: 'passive',
		description: 'Бонус увеличивается до +4.' },
	{ id: 'one_handed_stance', name: 'Боевая стойка', skillId: 'one_handed', tier: 2, type: 'passive',
		description: 'Силовые атаки тратят на 1 бодрость меньше.' },
	{ id: 'one_handed_quick', name: 'Быстрая атака', skillId: 'one_handed', tier: 2, type: 'passive',
		description: 'При быстрой атаке (два удара) +5 к попаданию.' },
	{ id: 'one_handed_strong3', name: 'Сильная рука III', skillId: 'one_handed', tier: 3, type: 'passive',
		description: 'Бонус увеличивается до +6.' },
	{ id: 'one_handed_stance2', name: 'Боевая стойка II', skillId: 'one_handed', tier: 3, type: 'passive',
		description: 'Силовые атаки тратят на 2 бодрости меньше (суммарно).' },
	{ id: 'one_handed_master', name: 'Мастер клинка', skillId: 'one_handed', tier: 3, type: 'reaction',
		description: 'Парируете одну атаку в ближнем бою. Тратите 2 бодрости.' },

	// ─── Стрельба ───
	{ id: 'archery_base', name: 'Базовый эффект', skillId: 'archery', tier: 0, type: 'passive',
		description: 'Каждое очко: +1 к урону и +1 к попаданию стрелковым оружием.' },
	{ id: 'archery_tension', name: 'Избыточное натяжение', skillId: 'archery', tier: 1, type: 'passive',
		description: 'Атака и урон увеличиваются на +2.' },
	{ id: 'archery_tension2', name: 'Избыточное натяжение II', skillId: 'archery', tier: 2, type: 'passive',
		description: 'Бонус увеличивается до +4.' },
	{ id: 'archery_eagle_eye', name: 'Орлиный взор', skillId: 'archery', tier: 2, type: 'passive',
		description: 'Штраф за стрельбу на Глубь уменьшается на 5.' },
	{ id: 'archery_steady_hand', name: 'Твёрдая рука', skillId: 'archery', tier: 2, type: 'passive',
		description: 'Модификатор стрельбы добавляется к урону дважды.' },
	{ id: 'archery_thrifty', name: 'Бережливый охотник', skillId: 'archery', tier: 2, type: 'passive',
		description: 'Не портите шкуру существа: +1к4 к добыче ресурсов.' },
	{ id: 'archery_tension3', name: 'Избыточное натяжение III', skillId: 'archery', tier: 3, type: 'passive',
		description: 'Бонус увеличивается до +6.' },
	{ id: 'archery_eagle_eye2', name: 'Орлиный взор II', skillId: 'archery', tier: 3, type: 'passive',
		description: 'Штраф на Глубь уменьшается на 10.' },
	{ id: 'archery_steady_hand2', name: 'Твёрдая рука II', skillId: 'archery', tier: 3, type: 'passive',
		description: 'Модификатор стрельбы добавляется к урону трижды.' },
	{ id: 'archery_rapid', name: 'Быстрая стрельба', skillId: 'archery', tier: 3, type: 'passive',
		description: 'Быстрая атака — 3 выстрела (+5 к попаданию), обычная — 2 выстрела (+10 к попаданию).' },

	// ─── Атлетика ───
	{ id: 'athletics_base', name: 'Базовый эффект', skillId: 'athletics', tier: 0, type: 'passive',
		description: 'Каждое очко навыка увеличивает результат проверок Атлетики на +1.' },
	{ id: 'athletics_jump', name: 'Сильный прыжок', skillId: 'athletics', tier: 1, type: 'passive',
		description: 'Прыжки: с места — 2 сажени, с разбега — 4 сажени.' },
	{ id: 'athletics_runner', name: 'Ловкий бегун', skillId: 'athletics', tier: 1, type: 'passive',
		description: 'При беге (трата бодрости) +2 сажени дополнительного перемещения.' },
	{ id: 'athletics_climber', name: 'Альпинист', skillId: 'athletics', tier: 2, type: 'passive',
		description: 'Взбираетесь по вертикальным поверхностям со скоростью 4 сажени за ход, тратя 1 бодрость.' },
	{ id: 'athletics_swimmer', name: 'Пловец', skillId: 'athletics', tier: 2, type: 'passive',
		description: 'Плаваете со скоростью 8 саженей за ход, не тратя бодрость.' },
	{ id: 'athletics_push', name: 'Толчок', skillId: 'athletics', tier: 2, type: 'active',
		description: 'Отталкиваете противника на 2 сажени (Избавление Силы).' },
	{ id: 'athletics_mountaineer', name: 'Скалолаз', skillId: 'athletics', tier: 3, type: 'passive',
		description: 'Перемещаетесь по отвесным стенам и потолку со скоростью 4 сажени, тратя 1 бодрость за ход.' },
	{ id: 'athletics_charge', name: 'Сокрушительный забег', skillId: 'athletics', tier: 3, type: 'active',
		description: 'Полный ход. Рывок до 12 саженей по прямой, сбивая всех на пути (Избавление Силы).' },

	// ─── Стойкость ───
	{ id: 'fortitude_base', name: 'Базовый эффект', skillId: 'fortitude', tier: 0, type: 'passive',
		description: 'Каждое очко: +1 к избавлению Силы против ядов, болезней и истощения.' },
	{ id: 'fortitude_strong_body', name: 'Крепкое тело', skillId: 'fortitude', tier: 1, type: 'passive',
		description: '+5 к избавлению против Отравы, Болезни и Истощения.' },
	{ id: 'fortitude_strong_body2', name: 'Крепкое тело II', skillId: 'fortitude', tier: 2, type: 'passive',
		description: 'Бонус +10. Живучесть: максимум +10.' },
	{ id: 'fortitude_slow_death', name: 'Медленная смерть', skillId: 'fortitude', tier: 2, type: 'passive',
		description: 'При 0 живучести не теряете сознание, пока не получите доп. урон, равный уровню.' },
	{ id: 'fortitude_strong_body3', name: 'Крепкое тело III', skillId: 'fortitude', tier: 3, type: 'passive',
		description: 'Бонус +15. Живучесть: максимум +20 (суммарно).' },
	{ id: 'fortitude_invuln', name: 'Неуязвимость', skillId: 'fortitude', tier: 3, type: 'active',
		description: '1/день. Игнорируете все эффекты избавления Силы на 1 минуту. Стоит 2 бодрости.' },

	// ═══════════════ ЛОВКОСТЬ ═══════════════

	// ─── Лёгкая броня ───
	{ id: 'light_armor_base', name: 'Базовый эффект', skillId: 'light_armor', tier: 0, type: 'passive',
		description: 'Каждое очко: +1 к Броне от лёгкой брони (не более +6) и +1 к Скрытности.' },
	{ id: 'light_armor_defense', name: 'Ловкость в обороне', skillId: 'light_armor', tier: 1, type: 'passive',
		description: 'Броня от лёгкой брони увеличивается на +2.' },
	{ id: 'light_armor_defense2', name: 'Ловкость в обороне II', skillId: 'light_armor', tier: 2, type: 'passive',
		description: 'Бонус +4. Вторая кожа: нет помех на Скрытность от брони. Крылья ветра: +2 бодрости.' },
	{ id: 'light_armor_defense3', name: 'Ловкость в обороне III', skillId: 'light_armor', tier: 3, type: 'passive',
		description: 'Бонус +6. Крылья ветра: +4 бодрости (суммарно).' },
	{ id: 'light_armor_dodger', name: 'Ловкий боец', skillId: 'light_armor', tier: 3, type: 'reaction',
		description: 'Реакция. Полностью уклоняетесь от одной атаки (без проверки). 2 бодрости. 1/бой.' },

	// ─── Скрытность ───
	{ id: 'stealth_base', name: 'Базовый эффект', skillId: 'stealth', tier: 0, type: 'passive',
		description: 'Каждое очко даёт +1 к проверкам Скрытности.' },
	{ id: 'stealth_light_step', name: 'Лёгкий шаг', skillId: 'stealth', tier: 1, type: 'passive',
		description: '+2 к Скрытности.', skillBonus: 2, progressiveGroup: 'stealth_step' },
	{ id: 'stealth_light_step2', name: 'Лёгкий шаг II', skillId: 'stealth', tier: 2, type: 'passive',
		description: '+4 к Скрытности.', skillBonus: 4, progressiveGroup: 'stealth_step' },
	{ id: 'stealth_muffled', name: 'Приглушённые шаги', skillId: 'stealth', tier: 2, type: 'passive',
		description: 'Шум от доспехов уменьшен вдвое для проверок обнаружения.' },
	{ id: 'stealth_backstab', name: 'Удар в спину', skillId: 'stealth', tier: 2, type: 'active',
		description: 'Атака из скрытности наносит двойной модификатор одноручного оружия. Стоит 4 бодрости.' },
	{ id: 'stealth_light_step3', name: 'Лёгкий шаг III', skillId: 'stealth', tier: 3, type: 'passive',
		description: '+6 к Скрытности.', skillBonus: 6, progressiveGroup: 'stealth_step' },
	{ id: 'stealth_backstab2', name: 'Удар в спину II', skillId: 'stealth', tier: 3, type: 'active',
		description: 'Бонус — тройной модификатор. Стоит 6 бодрости.' },
	{ id: 'stealth_silence', name: 'Тишина', skillId: 'stealth', tier: 3, type: 'passive',
		description: 'При беге вы не издаёте звуков.' },

	// ─── Взлом ───
	{ id: 'lockpicking_base', name: 'Базовый эффект', skillId: 'lockpicking', tier: 0, type: 'passive',
		description: 'Каждое очко даёт +1 к проверкам Взлома.' },
	{ id: 'lockpicking_tools', name: 'Отмычки', skillId: 'lockpicking', tier: 1, type: 'passive',
		description: 'Умеете пользоваться набором взломщика.' },
	{ id: 'lockpicking_master', name: 'Замочный мастер', skillId: 'lockpicking', tier: 1, type: 'passive',
		description: '+2 к проверкам Взлома.', skillBonus: 2, progressiveGroup: 'lockpicking_master' },
	{ id: 'lockpicking_master2', name: 'Замочный мастер II', skillId: 'lockpicking', tier: 2, type: 'passive',
		description: '+4 к проверкам Взлома.', skillBonus: 4, progressiveGroup: 'lockpicking_master' },
	{ id: 'lockpicking_wax', name: 'Восковой слепок', skillId: 'lockpicking', tier: 2, type: 'active',
		description: 'Копируете ключ за 5 бодрости и 10 минут.' },
	{ id: 'lockpicking_silent', name: 'Тихий взлом', skillId: 'lockpicking', tier: 2, type: 'passive',
		description: 'Взламываете замки бесшумно (без проверки на шум).' },
	{ id: 'lockpicking_master3', name: 'Замочный мастер III', skillId: 'lockpicking', tier: 3, type: 'passive',
		description: '+6 к проверкам Взлома.', skillBonus: 6, progressiveGroup: 'lockpicking_master' },
	{ id: 'lockpicking_eternal', name: 'Вечная отмычка', skillId: 'lockpicking', tier: 3, type: 'passive',
		description: 'Отмычки больше не ломаются при провале.' },
	{ id: 'lockpicking_trapmaster', name: 'Мастер ловушек', skillId: 'lockpicking', tier: 3, type: 'active',
		description: 'Обезвредить ловушку и использовать её против врагов. 1/день.' },

	// ─── Карманные кражи ───
	{ id: 'pickpocketing_base', name: 'Базовый эффект', skillId: 'pickpocketing', tier: 0, type: 'passive',
		description: 'Каждое очко даёт +1 к проверкам Карманных краж.' },
	{ id: 'pickpocketing_fingers', name: 'Ловкие пальчики', skillId: 'pickpocketing', tier: 1, type: 'passive',
		description: '+2 к Карманным кражам.', skillBonus: 2, progressiveGroup: 'pickpocket_fingers' },
	{ id: 'pickpocketing_fingers2', name: 'Ловкие пальчики II', skillId: 'pickpocketing', tier: 2, type: 'passive',
		description: '+4. В тени модификатор удваивается.', skillBonus: 4, progressiveGroup: 'pickpocket_fingers' },
	{ id: 'pickpocketing_night', name: 'Ночной вор', skillId: 'pickpocketing', tier: 2, type: 'passive',
		description: 'В тени модификатор Карманной кражи удваивается.' },
	{ id: 'pickpocketing_fast', name: 'Быстрая рука', skillId: 'pickpocketing', tier: 2, type: 'active',
		description: 'Карманная кража как часть разговора (проверка со штрафом −5).' },
	{ id: 'pickpocketing_fingers3', name: 'Ловкие пальчики III', skillId: 'pickpocketing', tier: 3, type: 'passive',
		description: '+6 к Карманным кражам.', skillBonus: 6, progressiveGroup: 'pickpocket_fingers' },
	{ id: 'pickpocketing_master', name: 'Мастер-карманник', skillId: 'pickpocketing', tier: 3, type: 'passive',
		description: 'Можете украсть предмет из открытой сумки на глазах (проверка −10).' },
	{ id: 'pickpocketing_all', name: 'Обчистить всех', skillId: 'pickpocketing', tier: 3, type: 'active',
		description: '1/день. Карманная кража у всех в радиусе 5 саженей за один ход. Стоит 10 бодрости.' },

	// ─── Алхимия ───
	{ id: 'alchemy_base', name: 'Базовый эффект', skillId: 'alchemy', tier: 0, type: 'passive',
		description: 'Каждое очко: +1 к кубу эффекта создаваемых зелий и ядов.' },
	{ id: 'alchemy_healer', name: 'Целитель', skillId: 'alchemy', tier: 1, type: 'passive',
		description: 'Умеете изготавливать зелья здоровья (1к6 живучести).' },
	{ id: 'alchemy_poisoner', name: 'Отравитель', skillId: 'alchemy', tier: 1, type: 'passive',
		description: 'Умеете изготавливать простые яды (1к4 урона).' },
	{ id: 'alchemy_skilled', name: 'Искусный алхимик', skillId: 'alchemy', tier: 2, type: 'passive',
		description: 'Эффективность зелий и ядов +1 куб.' },
	{ id: 'alchemy_conc_poison', name: 'Концентрированный яд', skillId: 'alchemy', tier: 2, type: 'passive',
		description: 'Яд на оружии держится вдвое дольше.' },
	{ id: 'alchemy_fast', name: 'Быстрое приготовление', skillId: 'alchemy', tier: 2, type: 'active',
		description: 'Простое зелье или яд за 10 минут (вместо 1 часа). Стоит 1 бодрости.' },
	{ id: 'alchemy_skilled2', name: 'Искусный алхимик II', skillId: 'alchemy', tier: 3, type: 'passive',
		description: 'Эффективность +2 куба (суммарно).' },
	{ id: 'alchemy_purity', name: 'Чистота', skillId: 'alchemy', tier: 3, type: 'passive',
		description: 'Зелья и яды применяют удвоенный модификатор Алхимии.' },
	{ id: 'alchemy_elixirs', name: 'Создание эликсиров', skillId: 'alchemy', tier: 3, type: 'active',
		description: 'Ритуал. Создаёте зелье с временным эффектом или снимающее проклятия.' },

	// ─── Уклонение ───
	{ id: 'evasion_base', name: 'Базовый эффект', skillId: 'evasion', tier: 0, type: 'passive',
		description: 'Каждое очко: +1 к Броне при уклонении и +1 к проверкам Уклонения.' },
	{ id: 'evasion_reflexes', name: 'Кошачьи рефлексы', skillId: 'evasion', tier: 1, type: 'passive',
		description: '+2 к проверкам Уклонения.', skillBonus: 2, progressiveGroup: 'evasion_reflexes' },
	{ id: 'evasion_reflexes2', name: 'Кошачьи рефлексы II', skillId: 'evasion', tier: 2, type: 'passive',
		description: '+4 к Уклонению.', skillBonus: 4, progressiveGroup: 'evasion_reflexes' },
	{ id: 'evasion_dodge', name: 'Нырнуть в сторону', skillId: 'evasion', tier: 2, type: 'reaction',
		description: '5 бодрости: мгновенно перемещаетесь на 4 сажени, уходя от атаки или области.' },
	{ id: 'evasion_fighter', name: 'Уклонившийся боец', skillId: 'evasion', tier: 2, type: 'passive',
		description: 'При уклонении (трата 2 бодрости на −15 к попаданию) можете сделать быструю атаку реакцией.' },
	{ id: 'evasion_reflexes3', name: 'Кошачьи рефлексы III', skillId: 'evasion', tier: 3, type: 'passive',
		description: '+6 к Уклонению.', skillBonus: 6, progressiveGroup: 'evasion_reflexes' },
	{ id: 'evasion_elusive', name: 'Неуловимость', skillId: 'evasion', tier: 3, type: 'passive',
		description: 'Если не атаковали в свой ход — +10 к Броне до начала следующего хода.' },
	{ id: 'evasion_death_dance', name: 'Смертельный танец', skillId: 'evasion', tier: 3, type: 'active',
		description: '1/бой. Раунд автоматического уклонения от всех атак. Стоит 13 бодрости.' },

	// ═══════════════ КРАСНОРЕЧИЕ ═══════════════

	// ─── Убеждение ───
	{ id: 'persuasion_base', name: 'Базовый эффект', skillId: 'persuasion', tier: 0, type: 'passive',
		description: 'Каждое очко даёт +1 к проверкам Убеждения.' },
	{ id: 'persuasion_gift', name: 'Дар слова', skillId: 'persuasion', tier: 1, type: 'passive',
		description: '+2 к Убеждению.', skillBonus: 2, progressiveGroup: 'persuasion_gift' },
	{ id: 'persuasion_iron', name: 'Железный аргумент', skillId: 'persuasion', tier: 1, type: 'active',
		description: '3 влияния: +10 к следующей проверке Убеждения в этом разговоре.' },
	{ id: 'persuasion_gift2', name: 'Дар слова II', skillId: 'persuasion', tier: 2, type: 'passive',
		description: '+4 к Убеждению.', skillBonus: 4, progressiveGroup: 'persuasion_gift' },
	{ id: 'persuasion_impossible', name: 'Невозможный договор', skillId: 'persuasion', tier: 2, type: 'active',
		description: 'Попытка убедить НПС против его интересов. Сложность +15.' },
	{ id: 'persuasion_aura', name: 'Аура авторитета', skillId: 'persuasion', tier: 2, type: 'active',
		description: '6 влияний: +5 к Убеждению против группы (до 5 человек) на 10 минут.' },
	{ id: 'persuasion_gift3', name: 'Дар слова III', skillId: 'persuasion', tier: 3, type: 'passive',
		description: '+6 к Убеждению.', skillBonus: 6, progressiveGroup: 'persuasion_gift' },
	{ id: 'persuasion_worldview', name: 'Изменение мировоззрения', skillId: 'persuasion', tier: 3, type: 'active',
		description: 'Ритуал (1 час). Изменить отношение ключевого НПС к идее. Проверка с +25. 1/сессию.' },
	{ id: 'persuasion_compromise', name: 'Идеальный компромисс', skillId: 'persuasion', tier: 3, type: 'passive',
		description: '+1 ко всем проверкам при взаимодействии с фракцией до конца приключения (после разрешения конфликта).' },

	// ─── Обман ───
	{ id: 'deception_base', name: 'Базовый эффект', skillId: 'deception', tier: 0, type: 'passive',
		description: 'Каждое очко даёт +1 к проверкам Обмана.' },
	{ id: 'deception_smooth', name: 'Гладкий язык', skillId: 'deception', tier: 1, type: 'passive',
		description: '+2 к Обману.', skillBonus: 2, progressiveGroup: 'deception_smooth' },
	{ id: 'deception_improv', name: 'Импровизация', skillId: 'deception', tier: 1, type: 'passive',
		description: 'Когда лжёте без подготовки — +5 к проверке.' },
	{ id: 'deception_smooth2', name: 'Гладкий язык II', skillId: 'deception', tier: 2, type: 'passive',
		description: '+4 к Обману.', skillBonus: 4, progressiveGroup: 'deception_smooth' },
	{ id: 'deception_mimicry', name: 'Виртуоз мимикрии', skillId: 'deception', tier: 2, type: 'active',
		description: '1 влияние: копируете манеру речи группы, +10 к Обману против них на 1 час.' },
	{ id: 'deception_legend', name: 'Сложная легенда', skillId: 'deception', tier: 2, type: 'active',
		description: 'Ритуал (1 час). Детализированное прикрытие: +10 к Обману для его поддержания.' },
	{ id: 'deception_smooth3', name: 'Гладкий язык III', skillId: 'deception', tier: 3, type: 'passive',
		description: '+6 к Обману.', skillBonus: 6, progressiveGroup: 'deception_smooth' },
	{ id: 'deception_master', name: 'Мастер иллюзии', skillId: 'deception', tier: 3, type: 'passive',
		description: 'Если проверка раскрытия лжи провалена с разницей < 10 — ложь сохраняется.' },
	{ id: 'deception_double_agent', name: 'Двойной агент', skillId: 'deception', tier: 3, type: 'active',
		description: 'Ритуал. Внедрение во враждебную организацию с проверкой Обмана +20.' },

	// ─── Запугивание ───
	{ id: 'intimidation_base', name: 'Базовый эффект', skillId: 'intimidation', tier: 0, type: 'passive',
		description: 'Каждое очко даёт +1 к проверкам Запугивания.' },
	{ id: 'intimidation_steel', name: 'Стальной взгляд', skillId: 'intimidation', tier: 1, type: 'passive',
		description: '+2 к Запугиванию.', skillBonus: 2, progressiveGroup: 'intimidation_steel' },
	{ id: 'intimidation_show', name: 'Демонстрация силы', skillId: 'intimidation', tier: 1, type: 'passive',
		description: 'Используя оружие или магию как угрозу — +5 к проверке Запугивания.' },
	{ id: 'intimidation_steel2', name: 'Стальной взгляд II', skillId: 'intimidation', tier: 2, type: 'passive',
		description: '+4 к Запугиванию.', skillBonus: 4, progressiveGroup: 'intimidation_steel' },
	{ id: 'intimidation_torture', name: 'Допрос с пристрастием', skillId: 'intimidation', tier: 2, type: 'active',
		description: 'Наносите 1к4 нелетального урона, чтобы получить преимущество на Запугивание.' },
	{ id: 'intimidation_warcry', name: 'Боевой клич', skillId: 'intimidation', tier: 2, type: 'active',
		description: 'Действие в бою. 2 влияния: цель проходит проверку против Запугивания, иначе −5 к следующей атаке.' },
	{ id: 'intimidation_steel3', name: 'Стальной взгляд III', skillId: 'intimidation', tier: 3, type: 'passive',
		description: '+6 к Запугиванию.', skillBonus: 6, progressiveGroup: 'intimidation_steel' },
	{ id: 'intimidation_aura', name: 'Аура Жути', skillId: 'intimidation', tier: 3, type: 'active',
		description: 'Действие в бою. Все враги в 10 м: проверка против Запугивания, иначе Жуть на 1 раунд. 3 влияния, 1/бой.' },
	{ id: 'intimidation_break', name: 'Сломить волю', skillId: 'intimidation', tier: 3, type: 'active',
		description: 'Ритуал. Сломить побеждённого врага: покорный слуга на 24 часа. Проверка +25, 5 влияний.' },

	// ─── Торговля ───
	{ id: 'trade_base', name: 'Базовый эффект', skillId: 'trade', tier: 0, type: 'passive',
		description: 'Каждое очко: +1 к Торговле и +2% к скидке/наценке (до +30%).' },
	{ id: 'trade_sense', name: 'Чутьё на выгоду', skillId: 'trade', tier: 1, type: 'passive',
		description: '+2 к Торговле.', skillBonus: 2, progressiveGroup: 'trade_sense' },
	{ id: 'trade_haggle', name: 'Торг', skillId: 'trade', tier: 1, type: 'active',
		description: '1 влияние: стандартная скидка 10% у торговца.' },
	{ id: 'trade_sense2', name: 'Чутьё на выгоду II', skillId: 'trade', tier: 2, type: 'passive',
		description: '+4 к Торговле.', skillBonus: 4, progressiveGroup: 'trade_sense' },
	{ id: 'trade_special', name: 'Особый заказ', skillId: 'trade', tier: 2, type: 'active',
		description: 'Уговорить торговца достать редкий (не магический) товар: цена +25%, 1к4 дней.' },
	{ id: 'trade_black_market', name: 'Чёрный рынок', skillId: 'trade', tier: 2, type: 'active',
		description: 'За 2 влияния и 1к6 часов найти продавца запрещённых товаров (наценка 50–100%).' },
	{ id: 'trade_sense3', name: 'Чутьё на выгоду III', skillId: 'trade', tier: 3, type: 'passive',
		description: '+6 к Торговле.', skillBonus: 6, progressiveGroup: 'trade_sense' },
	{ id: 'trade_invest', name: 'Инвестиции', skillId: 'trade', tier: 3, type: 'passive',
		description: 'Вложить деньги в торговлю: прибыль 10–50% после крупного приключения.' },
	{ id: 'trade_master', name: 'Мастер переговоров', skillId: 'trade', tier: 3, type: 'passive',
		description: 'Скидка 15% у всех не враждебных торговцев. 1/день: попытка скидки 25% за 13 влияний.' },

	// ─── Сплетничество ───
	{ id: 'gossip_base', name: 'Базовый эффект', skillId: 'gossip', tier: 0, type: 'passive',
		description: 'Каждое очко даёт +1 к Сплетничеству и ускоряет сбор слухов.' },
	{ id: 'gossip_ears', name: 'Навострённые уши', skillId: 'gossip', tier: 1, type: 'passive',
		description: '+2 к Сплетничеству.', skillBonus: 2, progressiveGroup: 'gossip_ears' },
	{ id: 'gossip_questions', name: 'Расспросы', skillId: 'gossip', tier: 1, type: 'active',
		description: 'За 1 влияние и 1 час в общественном месте узнаёте слухи и настроения.' },
	{ id: 'gossip_ears2', name: 'Навострённые уши II', skillId: 'gossip', tier: 2, type: 'passive',
		description: '+4 к Сплетничеству.', skillBonus: 4, progressiveGroup: 'gossip_ears' },
	{ id: 'gossip_informant', name: 'Ценный информатор', skillId: 'gossip', tier: 2, type: 'passive',
		description: 'Находите НПС — постоянный источник информации в этом городе.' },
	{ id: 'gossip_analysis', name: 'Анализ слухов', skillId: 'gossip', tier: 2, type: 'passive',
		description: 'Задаёте Мастеру уточняющий вопрос: правда, преувеличение или ложь.' },
	{ id: 'gossip_ears3', name: 'Навострённые уши III', skillId: 'gossip', tier: 3, type: 'passive',
		description: '+6 к Сплетничеству.', skillBonus: 6, progressiveGroup: 'gossip_ears' },
	{ id: 'gossip_network', name: 'Сеть осведомителей', skillId: 'gossip', tier: 3, type: 'passive',
		description: 'Получаете слухи из других локаций, не посещая их (5 влияний, 1 день).' },
	{ id: 'gossip_blackmail', name: 'Компромат', skillId: 'gossip', tier: 3, type: 'active',
		description: 'Ритуал. Собрать компромат на НПС: +10 к социальным проверкам против него на сюжетную арку. Проверка +20.' },

	// ═══════════════ РЕЛИГИЯ ═══════════════

	// ─── Молитва ───
	{ id: 'prayer_base', name: 'Базовый эффект', skillId: 'prayer', tier: 0, type: 'passive',
		description: 'Каждое очко: +1 к Молитве и +1 к силе божественных эффектов.' },
	{ id: 'prayer_faith', name: 'Искренняя вера', skillId: 'prayer', tier: 1, type: 'passive',
		description: '+2 к Молитве.', skillBonus: 2, progressiveGroup: 'prayer_faith' },
	{ id: 'prayer_sign', name: 'Просьба о знамении', skillId: 'prayer', tier: 1, type: 'active',
		description: '4 благодати: молитва о знаке, Мастер даёт туманную подсказку.' },
	{ id: 'prayer_faith2', name: 'Искренняя вера II', skillId: 'prayer', tier: 2, type: 'passive',
		description: '+4 к Молитве.', skillBonus: 4, progressiveGroup: 'prayer_faith' },
	{ id: 'prayer_bless', name: 'Благословение на дело', skillId: 'prayer', tier: 2, type: 'active',
		description: '3 благодати: благословляете группу (до 5 человек), +2 к одной проверке на выбор в течение 24 часов.' },
	{ id: 'prayer_purify', name: 'Ритуал очищения', skillId: 'prayer', tier: 2, type: 'active',
		description: 'Ритуал (10 минут). 8 благодати: снимаете Хворь или слабое Проклятие с себя или союзника.' },
	{ id: 'prayer_faith3', name: 'Искренняя вера III', skillId: 'prayer', tier: 3, type: 'passive',
		description: '+6 к Молитве.', skillBonus: 6, progressiveGroup: 'prayer_faith' },
	{ id: 'prayer_intervention', name: 'Божественное вмешательство', skillId: 'prayer', tier: 3, type: 'active',
		description: '1/кампанию. В момент крайней нужды: автоуспех критической проверки, неуязвимость (1 раунд) и т.п. Стоит ВСЕ благодати.' },
	{ id: 'prayer_holy_place', name: 'Священное место', skillId: 'prayer', tier: 3, type: 'active',
		description: 'Ритуал (8 часов). Освящаете помещение: нежить и демоны −10, союзники +1к4 живучести за короткий отдых. 1 неделю.' },

	// ─── Знания культов ───
	{ id: 'cult_base', name: 'Базовый эффект', skillId: 'cult_knowledge', tier: 0, type: 'passive',
		description: 'Каждое очко даёт +1 к проверкам Знаний культов.' },
	{ id: 'cult_theology', name: 'Богословские труды', skillId: 'cult_knowledge', tier: 1, type: 'passive',
		description: '+2 к Знаниям культов.', skillBonus: 2, progressiveGroup: 'cult_theology' },
	{ id: 'cult_symbol', name: 'Распознание символа', skillId: 'cult_knowledge', tier: 1, type: 'passive',
		description: 'Идентифицируете религиозный символ, божество и его базовую доктрину.' },
	{ id: 'cult_theology2', name: 'Богословские труды II', skillId: 'cult_knowledge', tier: 2, type: 'passive',
		description: '+4 к Знаниям культов.', skillBonus: 4, progressiveGroup: 'cult_theology' },
	{ id: 'cult_ritual', name: 'Понимание ритуала', skillId: 'cult_knowledge', tier: 2, type: 'passive',
		description: 'Наблюдая за ритуалом (или его следами), определяете цель и степень угрозы.' },
	{ id: 'cult_heresy', name: 'Слабость ереси', skillId: 'cult_knowledge', tier: 2, type: 'passive',
		description: '+10 к Убеждению или Запугиванию против адептов враждебных культов.' },
	{ id: 'cult_theology3', name: 'Богословские труды III', skillId: 'cult_knowledge', tier: 3, type: 'passive',
		description: '+6 к Знаниям культов.', skillBonus: 6, progressiveGroup: 'cult_theology' },
	{ id: 'cult_hide', name: 'Сокрытие веры', skillId: 'cult_knowledge', tier: 3, type: 'active',
		description: 'Маскируете свои религиозные практики под обряды другого культа. Проверка против Наблюдательности.' },
	{ id: 'cult_secrets', name: 'Древние тайны', skillId: 'cult_knowledge', tier: 3, type: 'passive',
		description: 'Знаете забытые знания о богах: истинные имена, слабости, места захоронения.' },

	// ─── Сила высших ───
	{ id: 'higher_base', name: 'Базовый эффект', skillId: 'higher_power', tier: 0, type: 'passive',
		description: 'Каждое очко: +1 к проверкам Силы высших и +1 к урону против нежити.' },
	{ id: 'higher_channel', name: 'Канал веры', skillId: 'higher_power', tier: 1, type: 'passive',
		description: '+2 к Силе высших.', skillBonus: 2, progressiveGroup: 'higher_channel' },
	{ id: 'higher_banish', name: 'Изгнание нечисти (малое)', skillId: 'higher_power', tier: 1, type: 'active',
		description: '8 благодати: попытка изгнать слабую нежить в радиусе 10 саженей.' },
	{ id: 'higher_channel2', name: 'Канал веры II', skillId: 'higher_power', tier: 2, type: 'passive',
		description: '+4 к Силе высших.', skillBonus: 4, progressiveGroup: 'higher_channel' },
	{ id: 'higher_bless_weapon', name: 'Благословение оружия', skillId: 'higher_power', tier: 2, type: 'active',
		description: '3 благодати: оружие союзника наносит +1к4 святого урона против нежити, демонов, проклятых.' },
	{ id: 'higher_aura', name: 'Аура святости', skillId: 'higher_power', tier: 2, type: 'active',
		description: '10 благодати: 3 раунда. Вы и союзники в 5 м получаете +2 к Броне и избавлению против магии тьмы и нежити.' },
	{ id: 'higher_channel3', name: 'Канал веры III', skillId: 'higher_power', tier: 3, type: 'passive',
		description: '+6 к Силе высших.', skillBonus: 6, progressiveGroup: 'higher_channel' },
	{ id: 'higher_banish_demon', name: 'Изгнание демона', skillId: 'higher_power', tier: 3, type: 'active',
		description: 'Полный ход. Сложная проверка. 8 благодати, 1/день. Существо получает 3к6 святого урона; при <50% живучести изгоняется.' },
	{ id: 'higher_judgment', name: 'Божественный приговор', skillId: 'higher_power', tier: 3, type: 'active',
		description: '13 благодати, 1/день. Враг получает 4к8 святого урона (половина при спасброске). Нежить и демоны — двойной урон.' }
];

export const ABILITIES_BY_SKILL: Record<string, Ability[]> = ABILITIES.reduce(
	(acc, a) => {
		if (!acc[a.skillId]) acc[a.skillId] = [];
		acc[a.skillId].push(a);
		return acc;
	},
	{} as Record<string, Ability[]>
);